// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWII2TP02.Data;

#nullable disable

namespace SWII2TP02.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SWII2TP02.Models.BL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Consignee");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Navio");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.HasKey("Id");

                    b.ToTable("BL");
                });

            modelBuilder.Entity("SWII2TP02.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tamanho");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Container");
                });
#pragma warning restore 612, 618
        }
    }
}
